# Setup
name:         Hardware security lab
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
theme: minima
